name: Java CI - Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java JDK 21 with Maven cache
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Compile and build the .jar file
      - name: Build with Maven
        run: mvn clean package

      # Copy the .jar file to the repository root
      - name: Copy jar to repository root
        run: cp target/*.jar .

      # Upload the .jar file as a workflow artifact
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
